services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: rigcraft_db
      POSTGRES_USER: rigcraft_user
      POSTGRES_PASSWORD: rigcraft_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - db

volumes:
  postgres_data:
