# Generated by Django 5.1.4 on 2026-06-18 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GPU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=50)),
                ('vram', models.IntegerField(help_text='e.g 8 is equall to 8 gigabyte VRAM')),
                ('tdp', models.IntegerField(help_text='Power usage base in watt')),
                ('benchmark_score', models.IntegerField(help_text='Approximate benchmark score')),
                ('length_mm', models.IntegerField(help_text='Physical length in millimeters')),
                ('price', models.IntegerField(help_text='Approximate price in iran market')),
                ('shop_url', models.URLField(help_text='Link to the shop')),
            ],
        ),
    ]
