# Generated by Django 5.1.4 on 2026-06-19 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=50)),
                ('supported_form_factors', models.CharField(help_text='e.g. ATX', max_length=100)),
                ('max_gpu_length_mm', models.IntegerField()),
                ('max_radiator_size_mm', models.IntegerField(blank=True, null=True)),
                ('price', models.IntegerField()),
                ('shop_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='CPU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=50)),
                ('socket', models.CharField(max_length=50)),
                ('tdp', models.IntegerField(help_text='Power usage in watt')),
                ('ddr_support', models.CharField(help_text='e.g. DDR4 or DDR5', max_length=20)),
                ('benchmark_score', models.IntegerField(help_text='Approximate score')),
                ('price', models.IntegerField(help_text='Approximate price in iran market')),
                ('shop_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='CPUCooler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=50)),
                ('cooler_type', models.CharField(help_text='AIO or Air', max_length=20)),
                ('tdp_support', models.IntegerField(help_text='Max TDP that it can cool')),
                ('socket_support', models.CharField(help_text="List of supported sockets comma seperated, e.g. 'LGA-1700, AM5'", max_length=200)),
                ('radiator_size_mm', models.IntegerField(blank=True, help_text='AIO models only', null=True)),
                ('price', models.IntegerField()),
                ('shop_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Motherboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=50)),
                ('socket', models.CharField(max_length=50)),
                ('ddr_support', models.CharField(max_length=20)),
                ('form_factor', models.CharField(help_text='e.g. ATX', max_length=20)),
                ('price', models.IntegerField()),
                ('shop_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='PSU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=50)),
                ('wattage', models.IntegerField()),
                ('efficiency_rating', models.CharField(help_text='e.g. 80+ Gold', max_length=30)),
                ('price', models.IntegerField()),
                ('shop_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='RAM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=50)),
                ('capacity_gb', models.IntegerField()),
                ('ddr_type', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('shop_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=50)),
                ('capacity_gb', models.IntegerField()),
                ('storage_type', models.CharField(help_text='NVMe or SATA', max_length=20)),
                ('price', models.IntegerField()),
                ('shop_url', models.URLField()),
            ],
        ),
    ]
