# Generated by Django 5.1.4 on 2026-06-19 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0002_case_cpu_cpucooler_motherboard_psu_ram_storage'),
    ]

    operations = [
        migrations.CreateModel(
            name='GPUBenchmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.CharField(max_length=100)),
                ('resolution', models.CharField(choices=[('1080p', '1080p'), ('1440p', '1440p'), ('4K', '4K')], max_length=10)),
                ('setting', models.CharField(choices=[('High', 'High'), ('Ultra', 'Ultra')], max_length=10)),
                ('fps', models.IntegerField()),
                ('gpu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benchmarks', to='components.gpu')),
            ],
        ),
    ]
